version: '3'

services:
  petalsync:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5000:5000"
    networks:
      - hostnet
    environment:
      MONGO_HOST: host.docker.internal
networks:
  hostnet:
    external: true
